name: Laravel Pint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    name: Run Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
